In [2]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [16]:
np.random.seed(12345)

In [22]:
dframe = DataFrame(np.random.randn(1000,4))

In [23]:
dframe

            0         1         2         3
0   -0.548465  0.909617  1.475824  0.584234
1   -0.573963  0.350913 -2.128789  1.008115
2   -0.550860 -1.385154 -0.408098  0.157126
3    0.558118  2.043916 -0.468581 -0.040791
4    1.561010 -0.012613  0.273331  0.469828
5    0.203006  0.386927 -0.454667  0.205434
6    1.150129 -1.403682  0.786843 -0.742125
7    0.653966  0.977491  0.577359  1.615828
8    0.029237  0.259463  0.925816 -0.245193
9    0.208011 -0.150923 -0.362528 -3.548824
10   1.553205 -2.186301  1.277104 -1.447885
11   1.241574 -0.522845  0.437207 -0.527700
12   1.095180 -1.507390  0.481187 -0.566726
13   0.746499  0.711985 -0.056769 -0.727258
14   0.225611  0.568654 -0.078101  0.103455
15   0.290124 -0.292404 -2.232314 -1.421750
16   2.615416 -0.261494 -0.663797  1.202837
17  -0.163063 -1.352346 -0.402064  1.858392
18   1.039311 -0.781186 -0.436587  1.251522
19   0.562882  0.049063  0.628928 -0.022082
20   0.259344 -0.516298 -0.579762 -1.351278
21  -0.229987 -0.799860 -0.693212  1.394392
22   0.136581 -0.827638 -0.901571  0.702082
23   1.213806 -1.242276 -1.751493  0.732649
24   0.288219 -1.065180 -0.911736  0.289077
25  -0.016887  1.494216 -0.100779  1.197297
26   1.724737  1.904455 -0.085071  0.834091
27   1.293456  0.666104 -0.739303 -1.494140
28  -0.212990  1.178550 -0.946819  0.027740
29  -0.680165  0.194637  0.674314 -1.357905
..        ...       ...       ...       ...
970 -0.011807  3.023720 -1.105312  0.105141
971  0.995257  0.808470 -0.306733 -1.586139
972 -0.836931  0.019669  2.138507  1.747473
973 -0.213868  0.162540 -2.215894 -1.842011
974 -0.149703  1.250328 -0.851648 -0.495212
975 -0.829868 -0.266819  0.455399  1.258675
976 -0.128850 -1.478753 -0.409701  1.292822
977  1.101135 -0.447069  0.456546 -0.719455
978 -0.699874  1.053949 -0.694457  0.542528
979 -1.906417  0.577897 -0.132023  0.638099
980 -0.122104 -0.551624 -0.318562  1.901837
981 -0.921032  0.452270  0.577097 -0.696937
982  1.524228 -0.179957 -0.248224  0.411191
983  1.866475  0.598080  0.633318  0.067528
984  0.459775  0.888282  0.277179  0.739166
985 -0.853504  0.942898  1.233265  0.358937
986  0.267060 -0.451634 -0.480407  0.298557
987  2.245758  0.296126  0.600710  0.489835
988 -0.045630 -0.195426 -0.450140 -0.272486
989  0.026010 -1.168152 -0.949609 -2.037458
990  0.725193  0.818536 -0.462278 -0.240876
991  0.299742  0.063121  0.521028 -1.038705
992  0.305150  0.612665 -0.759376  0.775080
993  1.201938  2.873075 -0.885162  0.093857
994 -0.205988 -0.823747 -0.330179 -2.246992
995 -0.770842  1.447091 -0.725269  0.729155
996 -1.858453  0.159774 -0.718588 -0.694012
997  1.398385  1.088053  1.308820 -1.365500
998  1.098708  0.062528  2.368010  0.452649
999 -3.481593  0.789944  1.737746 -0.875399

[1000 rows x 4 columns]

In [19]:
dframe.head()

          0         1         2         3
0  0.929616  0.316376  0.183919  0.204560
1  0.567725  0.595545  0.964515  0.653177
2  0.748907  0.653570  0.747715  0.961307
3  0.008388  0.106444  0.298704  0.656411
4  0.809813  0.872176  0.964648  0.723685

In [20]:
dframe.tail()

            0         1         2         3
995  0.493101  0.614967  0.423814  0.594771
996  0.508256  0.828686  0.861175  0.725067
997  0.954657  0.733794  0.488558  0.078268
998  0.368385  0.767890  0.525692  0.669292
999  0.658867  0.175471  0.734137  0.067593

In [24]:
dframe.describe()

                 0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.030822    -0.030280    -0.040649     0.004960
std       0.979781     0.964526     0.982923     1.023784
min      -3.481593    -3.194414    -3.108915    -3.645860
25%      -0.627153    -0.711668    -0.729106    -0.692060
50%       0.022671    -0.043096    -0.049977     0.038757
75%       0.690303     0.656860     0.618116     0.713369
max       3.525865     3.023720     3.366626     2.763474

In [25]:
col=dframe[0]

In [26]:
col.head()

0   -0.548465
1   -0.573963
2   -0.550860
3    0.558118
4    1.561010
Name: 0, dtype: float64

In [27]:
col[np.abs(col)>3]

248    3.525865
491   -3.333767
999   -3.481593
Name: 0, dtype: float64

In [28]:
dframe[(np.abs(dframe)>3).any(1)]

            0         1         2         3
9    0.208011 -0.150923 -0.362528 -3.548824
101  0.193299  1.397822  3.366626 -2.372214
248  3.525865  0.283070  0.544635  0.462204
268 -0.450721 -0.080332  0.599947 -3.645860
491 -3.333767 -1.240685 -0.650855  0.076254
572  0.344072  0.581893 -1.116332 -3.018842
597 -0.555434 -0.048478 -3.108915  1.117755
727 -0.217146 -0.274138  1.188742 -3.183867
774  0.744019  1.741426 -2.214074 -3.140963
940 -0.848098 -3.194414  0.077839 -1.733549
970 -0.011807  3.023720 -1.105312  0.105141
999 -3.481593  0.789944  1.737746 -0.875399

In [29]:
dframe[np.abs(dframe)>3] = np.sign(dframe)*3

In [30]:
dframe.describe()

                 0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.031112    -0.030109    -0.040907     0.006499
std       0.975334     0.963832     0.981384     1.018873
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.627153    -0.711668    -0.729106    -0.692060
50%       0.022671    -0.043096    -0.049977     0.038757
75%       0.690303     0.656860     0.618116     0.713369
max       3.000000     3.000000     3.000000     2.763474